name: Playwright Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    services:
      parabank:
        image: parasoft/parabank
        ports:
          - 8080:8080
          - 9001:9001
        options: >-
          --health-cmd="curl -f http://localhost:8080/parabank/index.htm || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          WEB_URL: http://localhost:8080/parabank/
          API_BASE_URL: http://localhost:8080/parabank/services/bank/
          ENV: ci
        run: npx playwright test --shard=${{ matrix.shard }}/2

      # Upload results (IMPORTANT)
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: allure-results-${{ matrix.shard }}
          path: allure-results
  
  merge-reports:
    name: Merge and Generate Report
    if: ${{ !cancelled() }}
    needs: test   # 🔥 ensures all shards finish first
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # 📥 Download all shard artifacts
      - uses: actions/download-artifact@v6
        with:
          path: allure-results

      # 🧹 Merge all results
      - name: Merge results
        run: |
          mkdir merged-results
          find allure-results -name "*.json" -exec cp {} merged-results \;

      # 📊 Generate Allure report
      - name: Generate report
        run: |
          npm install -g allure-commandline
          allure generate merged-results -o allure-report

      # 📤 Upload final report
      - uses: actions/upload-artifact@v6
        with:
          name: allure-report
          path: allure-report